name: 'Setup for Ember tests'
description: 'Setup a Node.js environment and prepare it to run Ember tests'
author: 'Francesco Novy'
branding:
  icon: 'package'
  color: 'blue'
runs:
  using: 'node12'
  main: 'index.js'
