name: Ember CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: rwjblue/setup-volta@v1
      - name: Verify node & yarn versions
        run: node -v && yarn -v
      - name: adding matchers
        uses: ./
      - name: Verify problem matchers
        run: yarn debug-problem-matchers
